# name: mkdocs_mike
# on:
#   push:
#     branches:
#       - master
# permissions:
#   contents: read

# jobs:
#   logingit:
#     runs-on: self-hosted
#     steps:
#       - name: Login to Github Packages
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#   buildimage:
#     runs-on: self-hosted
#     needs: [logingit]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Print current directory contents
#         run: ls -la ./docker_mkdocs/
#       - name: Build image
#         run: docker build -f ./Dockerfile-mike -t mkdocs_mike:latest .


name: mkdocs_mike
on:
  push:
    branches:
      - master
permissions:
  contents: read

env:
  DOCKER_PATH: /docker_mkdocs/

jobs:
  logingit:
    runs-on: self-hosted
    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  buildimage:
    env:
      DOCKER_PATH: ${{ env.DOCKER_PATH }}
    runs-on: self-hosted
    needs: [logingit]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -f Dockerfile_mike -t mkdocs_mike:latest .
