name: mkdocs_mike
on:
  push:
    branches:
      - master
permissions: 
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Add custom path
        run: |-
          export PATH=$PATH:/docker_mkdocs/
      - name: Build container
        run: docker build Dockerfile-mike



# name: ci 
# on:
#   push:
#     branches:
#       - master 
# permissions:
#   contents: write
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#         with:
#           python-version: 3.7
#       - uses: actions/cache@v2
#         with:
#           key: ${{ github.ref }}
#           path: .cache
#       - run: pip install mkdocs-material
#       - run: pip install mike 
#       - run: git fetch origin gh-pages --depth=1
#       - run: git config user.name ci-bot
#       - run: git config user.email leo.guilloux8+ci-bot@gmail.com
# #      - run: mkdocs gh-deploy --force


# # name: build
# # on:
# #   - master

# # env:
# #   NODE_VERSION: 14.x

# # permissions:
# #   contents: read

# # jobs:
# #   build:
# #     name: Build project
# #     runs-on: ubuntu-latest
# #     steps:

# #       - name: Checkout repository
# #         uses: actions/checkout@v3

# #       - name: Set up Node.js runtime
# #         uses: actions/setup-node@v3
# #         with:
# #           node-version: ${{ env.NODE_VERSION }}

# #       - name: Set up Node.js dependency cache
# #         uses: actions/cache@v3
# #         id: cache
# #         with:
# #           key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
# #           path: node_modules

# #       - name: Set up Node.js dependencies
# #         if: steps.cache.outputs.cache-hit != 'true'
# #         run: npm install

# #       - name: Check project
# #         run: npm run check

# #       - name: Build project
# #         run: |
# #           npm run build
# #           git diff --name-only