# name: mkdocs_mike
# on:
#   push:
#     branches:
#       - master
# permissions:
#   contents: read

# jobs:
#   logingit:
#     runs-on: self-hosted
#     steps:
#       - name: Login to Github Packages
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
  
#   buildimage:
#     runs-on: self-hosted
#     needs: [logingit]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Build image
#         run: |-
#           cd docker_mkdocs/Mike
#           ls -la 
#           docker build -t mkdocs_mike:latest .

#   pushimage:
#     runs-on: self-hosted
#     needs: [buildimage]
#     steps:
#       - name: Push image
#         run: |
#           echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
#           docker tag ${{ github.repository }}:build-temp ghcr.io/${{ github.repository }}:0.4
#           docker push ghcr.io/${{ github.repository }}:0.4
#           docker logout
#       - name: Clean up
#         run: docker image rm ${{ github.repository }}:build-temp ${{ github.repository }}:0.4