name: mkdocs_serve
on:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  logingit:
    runs-on: self-hosted
    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
  buildimage:
    runs-on: self-hosted
    needs: [logingit]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: |-
          if [ ${{ github.ref_name }} = 'master' ] ; then   $VARIABLE_TAG='devel' ; else  $VARIABLE_TAG = ${{github.ref_name}} ; fi
          cd docker_mkdocs/mkdocs_serve
          ls -la 
          docker build -t mkdocs_mike:$VARAIBLE_TAG .

  pushimage:
    runs-on: self-hosted
    needs: [buildimage]
    steps:
      - name: Push image
        run: |
          if [ ${{ github.ref_name }} = 'master' ] ; then   $VARIABLE_TAG='devel' ; else  $VARIABLE_TAG = ${{github.ref_name}} ; fi
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag ${{ github.repository }}:build-temp ghcr.io/${{ github.repository }}:$VARIABLE_TAG
          docker push ghcr.io/${{ github.repository }}:$VARIABLE_TAG
          docker logout
      - name: Clean up
        run: docker image rm ${{ github.repository }}:build-temp ${{ github.repository }}:$VARIABLE_TAG