name: mkdocs_mike
on:
  push:
permissions: write-all

jobs:
  
  logingit:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted
    steps:
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
  buildimage:
    runs-on: self-hosted
    needs: [logingit]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: |-
          cd docker_mkdocs/Mike 
          docker build -t mkdocs_mike:build-temp .

  pushimage:
    runs-on: self-hosted
    needs: [buildimage]
    steps:
      - name: Push image
        run: |
          if [ ${{ github.ref_name }} = "master" ]; then VARIABLE_TAG="devel"; else VARIABLE_TAG=${{github.ref_name}}; fi
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag mkdocs_mike:build-temp ghcr.io/${{ github.repository }}/mkdocs_mike:$VARIABLE_TAG
          docker push ghcr.io/${{ github.repository }}/mkdocs_mike:$VARIABLE_TAG
          docker logout
      - name: Clean up
        run: |
          if [ ${{ github.ref_name }} = "master" ]; then VARIABLE_TAG="devel"; else VARIABLE_TAG=${{github.ref_name}}; fi
          docker image rm mkdocs_mike:build-temp ghcr.io/${{ github.repository }}/mkdocs_mike:$VARIABLE_TAG